Alembic
AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum pull request #10
Opened 2021-10-24 21:23 UTC by AlexPunches

Добавил Алимбик и базовую миграцию базы и данных.
Добавил пункт про миграции в редми.

2021-10-24 22:18 UTC, AntonZelinsky requested changes

2021-10-24 22:18 UTC, AntonZelinsky commented on README.md
> +$ alembic upgrade 3f3caaaf8457
alembic upgrade head

2021-10-24 22:18 UTC, AntonZelinsky commented on README.md
Добавь ссылку на свой постман

2021-10-24 22:18 UTC, AntonZelinsky commented on alembic.ini
> +# file_template = %%(rev)s_%%(slug)s
Давай поменяем шаблон именования файлов на 
`file_template = %%(year)d-%%(month).2d-%%(day).2d-%%(hour).2d-%%(minute).2d-%%(second).2d_%%(rev)s_%%(slug)s`

2021-10-24 22:18 UTC, AntonZelinsky commented on migrations/versions/3f3caaaf8457_starting_data.py
> +    op.bulk_insert(cohorts_table,
Сделай отдельную пустую миграцию для вставки этих данных. И назови её как-то соответсвующе

2021-10-24 22:18 UTC, AntonZelinsky commented on migrations/versions/3f3caaaf8457_starting_data.py
> +Revision ID: 3f3caaaf8457
Удали и заново создай начальную миграцию, чтобы в названии файла появилась дата и время создания его. Иначе будет неконсистенто. Про это я написал ниже

2021-10-24 22:18 UTC, AntonZelinsky commented on alembic.ini
> +# file_template = %%(rev)s_%%(slug)s
Если так не сделать, то файлы будут иметь рандомные имена и не будет понятен порядок файлов

2021-10-24 22:18 UTC, AntonZelinsky commented on README.md
> +$ alembic upgrade 3f3caaaf8457
Так же, добавь команду для создания миграций

2021-10-24 22:18 UTC, AntonZelinsky commented on README.md
>  $ uvicorn app.main:app
И добавь альтернативную команду для запуска `python run.py`

2021-10-24 23:29 UTC, AlexPunches commented on README.md
постман надо как-то пограмотнее сделать, 
наверно, постепенно будем улучшать

2021-10-24 23:29 UTC, AlexPunches commented on alembic.ini
> +# file_template = %%(rev)s_%%(slug)s
и правда :)

2021-10-24 23:31 UTC, AlexPunches commented on README.md
>  $ uvicorn app.main:app
закралась опечатка в название EVENING_REMINDER_HOUR
поправил .env.example чтобы было как в коде

2021-10-24 23:45 UTC, AntonZelinsky approved these changes

2021-10-24 23:45 UTC, AntonZelinsky commented on README.md
> +При изменении структуры базы не забывай накатывать мигации
`Создавать и применять`

2021-10-24 23:45 UTC, AntonZelinsky commented on README.md
> +## Тестировать
Какой-то уж сильно броский заголовок

2021-10-24 23:45 UTC, AntonZelinsky commented on README.md
> +4. Накатить миграции
Накатить — плохое слово для документации

2021-10-25 00:01 UTC, AlexPunches commented on README.md
> +4. Накатить миграции
я как-то не смог приличное слово подобрать :)

2021-10-25 00:02 UTC, merged