Pydantic and config.py
AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum pull request #12
Opened 2021-10-26 13:45 UTC by inferno2f

- Добавлен файл конфига с тремя классами: базовый, для тестов и для прода
- Все переменные окружения теперь валидируются и достаются из файла конфига (вместо os.getenv())
- Для удобства переключения между настройками проекта используется булевая DEBUG_MODE
- Обновлен readme с учетом изменений

2021-10-27 14:39 UTC, AntonZelinsky requested changes

2021-10-27 14:39 UTC, AntonZelinsky commented on app/config.py
> +from pydantic import BaseSettings
Давай этот файл в папку кор перенесём.

2021-10-27 14:39 UTC, AntonZelinsky commented on app/config.py
> +config = {
Давай из [этого место украдём](https://github.com/AntonZelinsky/Catinder/blob/develop/app/config.py#L56) и названия конфигов и типы. Базовый подразумевает что он абстрактный и его использовать нельзя.
Нужен девелопмент, для локальной разработки, тестовый для тестового сервера и продакшен.

2021-10-27 14:39 UTC, AntonZelinsky commented on app/config.py
> +    sqlalchemy_database_url: str
В деве и тестовом флаг дебаг можно устанавливать по дефолту как тру. В продакшене как фолс

2021-10-27 14:39 UTC, AntonZelinsky commented on app/config.py
> +    notion_database_id: str
Мне кажется, эту штуку переделывали на несколько id и название даже поменялось. А потом, должны были сделать подгрузку из базы. @AlexPunches можешь подсказать что с этим значением

2021-10-27 14:39 UTC, AntonZelinsky commented on app/config.py
> +    domain_address: str
В зависимости от этого значения, у нас запустится сервер на вебхуках или на пулинге. Добавь пожалуйста об этом информацию в ридми и хорошо бы написать, что для разработки достаточно использовать пулинг. Чтобы не усложняли.

2021-10-27 14:39 UTC, AntonZelinsky commented on app/main.py
> +def get_settings():
Засовывай в отдельный роутер

2021-10-27 14:39 UTC, AntonZelinsky commented on app/main.py
> +def get_settings():
Это веб хук пока что тут, так как было не понятно как сделать инициализацию тут, а прокинуть в роутер. Однако, я уже знаю) скоро переделаем

2021-10-27 14:39 UTC, AntonZelinsky commented on app/main.py
> +settings = config['test']()
Эту штуку нужно засунуть в систему внедрения зависимостей и инжектать там где можно.   https://fastapi.tiangolo.com/advanced/settings/#creating-the-settings-only-once-with-lru_cache

По хорошему, эту штуку можно положить прямо в коре, даже в файле с конфигами, чтобы всё в одном месте было.

2021-10-27 14:39 UTC, AntonZelinsky commented on app/main.py
> +settings = config['test']()
И только не нужно хардкодить тестинг, а нужно обратиться в .env файл и посмотреть что там установлено

2021-10-27 17:05 UTC, AlexPunches commented on app/config.py
> +    notion_database_id: str
эта переменная просто будет не нужна, она сейчас как временная заглушка. Немного позже эти айдишники будут в БД

2021-11-01 14:44 UTC, AntonZelinsky approved these changes

2021-11-01 14:44 UTC, AntonZelinsky commented on app/routers/settings.py
> +def get_settings(settings=Depends(config.get_settings())):
А зачем нам нужно отдавать эти данные на фронт?

2021-11-01 14:44 UTC, AntonZelinsky commented on core/config.py
> +    if BaseConfig().debug:
А как попасть на третий TestConfig?

2021-11-01 14:46 UTC, merged