Make creator cohotrs in Notions
AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum pull request #13
Opened 2021-10-26 15:51 UTC by AlexPunches

в `.env` добавилась константа `NOTION_PAGE_ID=`
Это родительская страница ноушена, на которой создаются `Databases` когорт (календари)

Собстно, чтобы создать когорту, отправляем ее название на ендпоинт /cohorts/
```
{
    "name": "38 когорта. Python-разработчик"
}
```
это создаст когорту в базе, 
тутже создаст календарь в ноушене и получит его `UUID`,
и добавит `UUID` календаря к когорте в бд.

Код вроде как работает,
Но мне кажется можно его сделать красивее :)

Как тут можно улучшить?

**ЗЫ**
в прошлой версии миграций был небольшой косяк, возможно добавление когор пару раз выдаст ошибку 500,
сейчас миграции без ошибки

**ЗЗЫ**
функция `is_databases_by_cohort_name()` в `notion.py`
нормально ли использовать такие конструкции?
`db['title'][0]['text']['content']`

2021-10-28 12:52 UTC, AntonZelinsky commented on app/routers/cohorts.py
> +        db_cohort = services.get_cohort_by_name(self.db, name=cohort.name)
Сделай метод в сервисе, который будет возвращать труфолс, незачем получать всю строку

2021-10-28 12:52 UTC, AntonZelinsky commented on app/routers/users.py
> +            )
Вынеси это тоже в отдельный метод, и просто используй его здесь. 
Но этим методом будет пользоваться бот, а там ловить эксепшены плохой вариант. ну, пусть будет пока, однако когда дойдём до создания пользователя в боте, подумаем как соблюсти **принцип идемпотентности**

2021-10-28 12:52 UTC, AntonZelinsky commented on migrations/versions/2021-10-26-11-34-08_43315bdbe41f_uniq_notion_id.py
> +"""uniq-notion-id
чувствую, будут конфликты в миграциях, так как Влад снёс всё и создал по новой

2021-10-29 16:43 UTC, AlexPunches commented on migrations/versions/2021-10-26-11-34-08_43315bdbe41f_uniq_notion_id.py
> +"""uniq-notion-id
надо будет на мои заменить, 
они актуальные, 
если я в них еще не успел накосячить :)

2021-10-29 16:45 UTC, AlexPunches commented
заменил мезанизмы добавления когорт, на механизмы синхронизации из ноушена.

пока повесил синхронизацию на эндпоинт GET /cohorts/sync/,
потом уже решим как будем запускать ее

2021-10-30 08:28 UTC, AlexPunches commented
удалил синхронизацию, 
сейчас когорты добавляются пост-запросом на эндпоинт `/cohorts/`

2021-10-30 15:43 UTC, AntonZelinsky requested changes

2021-10-30 15:43 UTC, AntonZelinsky commented on app/services.py
> +def has_user_by_telegram_id(db: Session, telegram_id: int) -> bool:
Я отписывался в твоём первом ПРе, но отпишусь и тут, тот закрою. Сделай пожалуйста два класса, один из которых будет работать только с юзерами, а другой с когортами

2021-10-30 15:43 UTC, AntonZelinsky commented on .env.example
> +NOTION_PAGE_ID=
Это значение нигде не используется

2021-10-30 15:43 UTC, AntonZelinsky commented on app/services.py
> +    if has_cohort_by_uuid(db, str(cohort.notion_db_id)):
Приводи тогда к строе непосредственно перед запросом в базу. 
А вообще, проблема в том, что тип в базе у тебя строка, а по хорошему, должен быть юидом.
https://github.com/AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum/pull/13/files#diff-880083c8a05dc4662af880cde1cf569e18f4476182e8680d2cee4cf1281a3d6eR26

2021-10-30 15:43 UTC, AntonZelinsky commented on app/services.py
>      db.refresh(db_cohort)
мне кажется, рефреш делать не обязательно, он сам обновит модель при комите, хотя, может я чего-то не знаю

2021-10-30 15:43 UTC, AntonZelinsky commented on core/models.py
> +    notion_db_id = Column(String, unique=True)
если в ноушене uuid, то тут тоже лучше поменять

2021-10-30 15:43 UTC, AntonZelinsky commented on notion.py
> +def query_databases_by_str(query: str):
Если этот метод больше не используется, то по хорошему, нужно удалить. Так как этот метод заточен только под получение страниц

2021-10-30 15:43 UTC, AntonZelinsky commented on app/routers/cohorts.py
> +        except ValueError as e:
Тут не нужно перехватывать исключение. Нужно перед созданием когорты вызвать метод `has_cohort_by_uuid` и если есть, то вернуть сообщение об ошибке, можно даже с кодом 400, если нет, то создавать. В методе проверка повторится, если там упадёт, тогда такая судьба.

2021-11-01 23:22 UTC, AlexPunches commented on app/services.py
> +    if has_cohort_by_uuid(db, str(cohort.notion_db_id)):
исправил в базе на uuid, 
но пришлось менять первую миграцию, 
не сомг сам написать миграцию для изменения поля на uuid :(

2021-11-01 23:24 UTC, AlexPunches commented on app/services.py
>      db.refresh(db_cohort)
так и есть, обновляется сразу после коммита.

2021-11-01 23:27 UTC, AlexPunches commented on app/routers/cohorts.py
> +        except ValueError as e:
поправил, 
тепрь рейзят только сервисные функции

2021-11-01 23:29 UTC, AlexPunches commented on app/services.py
> +def has_user_by_telegram_id(db: Session, telegram_id: int) -> bool:
Что-то я туплю, не могу понять, что надо сделтаь. 

Разделил сервисы на классы, 
но мне кажется не так надо было сделать.

2021-11-01 23:33 UTC, AlexPunches commented
Обновил миграции. 
Нужно было изменить тип столбца. Но Алимбик это как-то автоматом не умеет. 
А с raw при uuid не так просто было разобраться :(
Поэтому я просто запилил новые миграции с нуля.

Это значит теперь старую базу надо удалить, и накатить миграции с нуля.
Ну т.е. удалить прям volum докера, и он сам сделает новую пустую базу.

2021-11-02 19:33 UTC, AntonZelinsky commented on app/services.py
> +        db_user = models.User(name=user.name, telegram_id=user.telegram_id)
А попробуйсоздание пользователя заменить такой конструкцией, по идее, они идентичные `models.User(**user)`

2021-11-05 04:37 UTC, AlexPunches commented on app/services.py
> +        db_user = models.User(name=user.name, telegram_id=user.telegram_id)
чет не получилось :(
я елси честно пока не очень понимаю пиновскую магию звездочек и других сахаров :)

что-то надо подправить наверно, пидантиковскую штуку не распаковывает

2021-11-05 12:48 UTC, AntonZelinsky commented on app/services.py
> +        db_user = models.User(name=user.name, telegram_id=user.telegram_id)
Окей, тут важно, чтобы параметры совпадали, если что-то не так, то работать не будет.

2021-11-05 13:55 UTC, AntonZelinsky approved these changes

2021-11-05 13:55 UTC, AntonZelinsky commented on app/routers/users.py
> +    def read_users(self, service: UserService = Depends()):
Супер, давай только ещё сделаем так, чтобы сервис инжектался в ласс, а не в метод. Так код будет намного красивее.
Ты уже делал такое в UserService или вот пример как сделать красиво https://fastapi-utils.davidmontague.xyz/user-guide/class-based-views/#the-cbv-decorator

2021-11-05 13:55 UTC, AntonZelinsky commented on app/services.py
> +        self.limit = limit
Как я понимаю, эти параметры используются только для функции get_users, к тому же, они туда инжектаются напрямую. 
Я предлагаю их отсюда удалить, впрочем как и получении сессии и сделать как я привёл в примере выше. Так код будет лаконичнее и красивее.

2021-11-06 10:50 UTC, AlexPunches commented on app/routers/users.py
> +    def read_users(self, service: UserService = Depends()):
с этим вроде разобрался

2021-11-06 10:55 UTC, AlexPunches commented on app/services.py
> +        self.limit = limit
вроде сделал как смог понять )
небольшой вопрос остался, перенесу его в слак.

2021-11-07 18:24 UTC, AntonZelinsky approved these changes

2021-11-07 18:24 UTC, AntonZelinsky commented on app/services.py
> +    def __init__(self, db: Session = Depends(get_db)):
Смысла от этой абстракции не очень много, но раз сделал, то пусть будет.

2021-11-07 18:24 UTC, merged