Feature/add user [Conversation Handler]
AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum pull request #14
Opened 2021-11-03 14:51 UTC by inferno2f

Что нового:
- Реализован Conversation Handler, который проводит онбординг для новых юзеров.
- На данный момент бот запрашивает и получает имя юзера, а так же его почту.
- Добавлены кнопки для изменения адреса почты и повторной отправки подтверждения

Предлагается к дальнейшему внедрению:
- Regex фильтр для проверки корректности формата введенного имейла

P.S:
немного доработан файл конфига, за более подробным описанием читай README

2021-11-03 15:49 UTC, AntonZelinsky requested changes

2021-11-03 15:49 UTC, AntonZelinsky commented on core/config.py
> +    env = BaseConfig().environment
Что будет, если инвайрмент введён неправильно и такого у нас нет?)

2021-11-03 15:49 UTC, AntonZelinsky commented on core/config.py
> -    debug: bool = False
Нам больше не нужен режим отладки? домен ты в базовый конфиг перенёс, а дебага там нет, к тому же, он явно должен быть отключен тут. Если он конечно вообще используется в приложении)

2021-11-03 15:49 UTC, AntonZelinsky commented on bot/__init__.py
> +NAME, EMAIL = range(2)
Не используй цифры, только строковые понятные человеку значения.
Это очень плохая практика использования цифр, при отладке ты увидишь цифру, а не простой и понятный ключ. Я на проекте по прочарити проталкивал эту штуку, хоть было на тот момент не понятно где они могут быть видны, ведь в отладке базового приложения эти штуки передаются только внутрь приложения. Однако, позже, когда мы словили баг который все члены команды отлаживали по много часов и не могли найти причину, в том числе и я, но как раз благодаря понятным строкам и получилось найти решение. Если бы были цифры, не знаю что бы было

2021-11-03 15:49 UTC, AntonZelinsky commented on bot/__init__.py
> +NAME, EMAIL = range(2)
Скорее всего в тот момент пришлось бы переделать)

2021-11-03 15:49 UTC, AntonZelinsky commented on README.md
> +```DOMAIN_ADDRESS``` вам может пригодиться только в режимах ```test``` и ```production```.
А если я хочу локально запустить режим вебхуков?

2021-11-03 15:49 UTC, AntonZelinsky commented on core/config.py
> +    env = BaseConfig().environment
Нужно по дефолту выбирать девелопмент и всегда логировать какой инвайрмент выбран

2021-11-03 15:49 UTC, AntonZelinsky commented on .env.example
> -SQLALCHEMY_DATABASE_URL=
Должна быть возможность поменять адрес базы данных и домен

2021-11-03 15:49 UTC, AntonZelinsky commented on bot/__init__.py
> +REPLY_KEYBOARD = [['Отправить письмо повторно', 'Изменить адрес почты']]
Посмотри как сделаны кнопки в проекте который я присылал тебе раньше.  намного лучше использовать CallbackQueryHandler.
Если нужно сделать внутри какое-то ветвление, то лучше сделай ещё один метод, потом подумаем как объединить

2021-11-03 15:49 UTC, AntonZelinsky commented on bot/__init__.py
> +        request_email(update=update, context=context)
Не делаем спагетти код. Лушче продублировать, потом придумаем как оптимизировать

2021-11-03 15:49 UTC, AntonZelinsky commented on core/config.py
> +    env = BaseConfig().environment
Увидел в конфиге дефолт, если так всё работает, то окей. Но если такого конфига нет, то нужно бросать исключение

2022-01-05 15:31 UTC, AntonZelinsky commented on bot/__init__.py
> +def init_polling(token):
👍🏻

2022-01-05 15:31 UTC, AntonZelinsky commented on handlers/conversation_handlers.py
> +        EMAIL: [
Состояние лучше назвать ASK_EMAIL. И файл с константами переименовать на состояния. И импортировать файл, а к нему обращаться для получения константы `states.ASK_EMAIL`. Так намного проще воспринимать их в тексте.

2022-01-05 15:31 UTC, AntonZelinsky commented on handlers/conversation_handlers.py
> +def request_email(update, context):
Давай разделим на 2 функции, чтобы убрать проверки и сделать код более прямолинейным. Потом подумаем как можно объединить.

2022-01-05 15:31 UTC, AntonZelinsky commented on handlers/conversation_handlers.py
> +    fallbacks=[CallbackQueryHandler(edit_details)]
Фолбэк убрать, он пока не нужен.

2022-01-06 22:52 UTC, AntonZelinsky commented on handlers/conversation_handlers.py
> +    logging.info(f"Пользователь выбрал никнейм: {username}")
Тогда уже добавить id пользователя, чтобы можно было по логам отследить действия пользователя.

2022-01-06 22:52 UTC, AntonZelinsky commented on handlers/conversation_handlers.py
> +            )
Давай длину строки сделаем 120 по дефолту. Можно в файле [сетап ](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/setup.cfg#L22)настроить. Они должны подтянуться в ide

2022-01-06 22:52 UTC, AntonZelinsky commented on handlers/conversation_handlers.py
> +RESEND_CONF_LINK = "resend_email"
Давай эти переменные тоже в отдельный файл вынесем, назовём их команды.

2022-01-06 22:52 UTC, AntonZelinsky commented on handlers/conversation_handlers.py
> +        states.UPDATE_DATA: [
Давай переименуем на WAITING_CONFIRM

2022-01-06 22:52 UTC, AntonZelinsky commented on handlers/conversation_handlers.py
> +                check_user_data, pass_user_data=True, pass_chat_data=True
В документации написано, что  устаревшие. Если честно, я не понял за чем они тут нужно
https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.callbackqueryhandler.html#telegram-ext-callbackqueryhandler

2022-01-06 22:52 UTC, AntonZelinsky commented on handlers/conversation_handlers.py
> +                check_user_data, pass_user_data=True, pass_chat_data=True
Долго пытался понять эту функцию и наконец дошло зачем ты её такой сделал. Один этот колбэк нужно заменить на  2, а функцию вовсе удалить.
```suggestion
                CallbackQueryHandler(confirmation_sent, pattern=RESEND_CONF_LINK)
                CallbackQueryHandler(change_email, pattern=UPDATE_EMAIL)
```

2022-01-07 07:37 UTC, inferno2f commented on handlers/conversation_handlers.py
> +                check_user_data, pass_user_data=True, pass_chat_data=True
Точно, так и надо было делать с самого начала.
Запутался с этим колбэк квери пока правил все.
Спасибо!

2022-01-07 14:16 UTC, merged