Improvement/fetch user info
AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum pull request #20
Opened 2022-01-28 09:39 UTC by inferno2f

- User info for daily reminders should now be fetched from DB (filtered by email from received from Notion API)
- Relative imports fixed
- Migration file fixed

2022-01-28 23:35 UTC, AntonZelinsky approved these changes
Хорошо, даже придраться не получается:)

2022-01-28 23:35 UTC, AntonZelinsky commented on app/routers/users.py
> +from app import schemas
👍🏻

2022-01-28 23:35 UTC, AntonZelinsky commented on bot/__init__.py
> +        if user.email:
Если емайла нет, то должно произойти что-то плохое! Сейчас можно просто залогировать с ошибкой

2022-01-28 23:35 UTC, AntonZelinsky commented on bot/__init__.py
> +                logging.info(f'Дежурный с имейлом {user.email} не найден в базе данных')
Уровень логирования должен ошибкой быть

2022-01-28 23:35 UTC, AntonZelinsky commented on app/services.py
> +        return self.db.query(models.User).filter(models.User.email == email)
Подозреваю, что фильтр возвращает список. Не понимаю как у тебя работает код 0_о )))
Если возвращает прямой объект, то отпишись, мне самому стало даже интересно

2022-01-28 23:35 UTC, AntonZelinsky commented on bot/__init__.py
> +                logging.info(f'Дежурный с имейлом {user.email} не найден в базе данных')
Данные должны браться из базы данных, а не из ноушена, из ноушена только email пользователя. В других местах тоже поправь.

2022-01-30 16:15 UTC, inferno2f commented on bot/__init__.py
> +        if user.email:
я правильно понимаю, что по-хорошему здесь лучше использовать конструкцию try-except?

2022-01-30 16:16 UTC, inferno2f commented on bot/__init__.py
> +                logging.info(f'Дежурный с имейлом {user.email} не найден в базе данных')
Ок, согласен! Как-то даже не задумался об этом, когда писал код

2022-01-30 16:17 UTC, inferno2f commented on app/services.py
> +        return self.db.query(models.User).filter(models.User.email == email)
Здесь опять же мой жесткий косяк... =(
Тут вообще возвращается объект типа Query, переделаю на человеческий вариант

2022-01-31 19:42 UTC, AlexPunches commented on app/api.py
> +from app.routers import cohorts, users
То что надо ;)

2022-01-31 21:48 UTC, AlexPunches reviewed
Прошу не принимать мое ревью как правильное, 
возможно я и сам напутал ))

2022-01-31 21:48 UTC, AlexPunches commented on app/services.py
> +    def get_user_by_email(self, email: str):
Я бы попробовал `email: EmailStr` заюзать от пидантика,
если этот метод будет когда нибудь куда нибудь наружу, то возможно EmailStr окажется юзабельнее, хз

2022-01-31 21:48 UTC, AlexPunches commented on bot/__init__.py
> +            return mentor, cohorts, user
Мне кажется тут мы выйдем на первой итерации?

mentor и user -- это наставник в разных местах (в БД и в ноушене)
Мне кажется, мы уже можем строить приложение с приоритетом на БД, в ней у нас будет достаточно данных: и телега, и мыло, и имя, и notion_user_id чтобы связать с ноушеном. А в ноушене напротив, возможно чего-то не будет.
Т.е. мне кажется будет удобно и достаточно если наши функции будут обмениваться объектами `models.User`

2022-01-31 21:48 UTC, AlexPunches commented on bot/__init__.py
> +    try:
Почему-то мне кажется, что у `fetch_mentor_from_database` и `send_message` могу быть свои исключения.
Или я что-то упускаю из внимания в контексте запущенного бота?

2022-01-31 21:48 UTC, AlexPunches commented on migrations/versions/2022-01-10-00-34-23_6270cbc9981c_add_registrations.py
> -    sa.PrimaryKeyConstraint('uuid')
тут должен быть 
`sa.PrimaryKeyConstraint('confirmation_code')`
но это мой косяк ;)
поправлю в будущем ПР

2022-01-31 21:48 UTC, AlexPunches commented on notion.py
> +                # print(name[0].plain_text)
можно удалить наверно ;)
Помню, ревьюеры ругали за код в комментах

2022-02-01 00:56 UTC, AntonZelinsky requested changes
Влад, посмотри что возвращает функция `get_users_data`. Насколько я вижу по функции `group_by_user_raw_data`, она возвращает словарь:
```
{ 
  'email1':
    {
            'name': 'name1',
            'email': 'email1',
            'telegram_id': '123',
            'databases': [user_data.database]
    }
```
databases судя по коду, это модели когорт.

Сейчас всё можно настолько упростить, что выкинуть функцию `group_by_user_raw_data` как избыточный код и делать всё сразу в `get_users_raw_data` (только переименовать её нужно будет, так как смысл возвращаемых значений поменяется). А вообще, нужно весь этот код переместить в get_users_data.
Возвращать из функции нужно будет уже другую структуру:
```
{
  'e@mail.com': [тут можно передавать просто список id, либо как сейчас, модель когорты]
}
```
Сделать это будет просто, смотри уже написанный код в этом файле.
Постарайся упростить код в функции получения данных.

2022-02-01 00:56 UTC, AntonZelinsky commented on bot/__init__.py
> +        mentor, cohorts, user = fetch_mentor_from_database(context)
Зачем тут нужен юзер? он нигде не используется

2022-02-01 00:56 UTC, AntonZelinsky commented on bot/__init__.py
> +            return mentor, cohorts, user
Саша на 100% прав. Для нас нужен ноушен только для того, чтобы получить email дежурного, дальше информация берётся из базы.

2022-02-01 00:56 UTC, AntonZelinsky commented on bot/__init__.py
> +            return mentor, cohorts, user
Ну да, и на первой итерации цикла приложение закончит свою работу, и уведомление будет отправлено только первому подходящему пользователю. Раньше алгоритм хорошо работал.

2022-02-01 00:56 UTC, AntonZelinsky commented on bot/__init__.py
> +            return mentor, cohorts, user
Влад, разберись как работает твой алгоритм, просто отладчиком пройдись по всем шагам. 
Как вариант, сделать всё генератором. Но тут при любом раскладе нужно будет добавить ещё один цикл в главной функции колбэках
почитай статейки
https://anton-zelinsky.notion.site/33609a0944054bafacdd9fb560f1b2f5
https://www.notion.so/anton-zelinsky/d533a31bf763498786a41b4d2e33abf2

2022-02-01 00:56 UTC, AntonZelinsky commented on bot/__init__.py
> +def fetch_mentor_from_database(context: CallbackContext):
Эта функция не относится к телеграм боту.  Тут по сути идёт получение дежурного у когорт. Значит, её нужно вынести в другое место, в сервис.
Наверно в сервис когорт, так как мы.

`context: CallbackContext` тут никак не используется, значит, не нужно его передавать внутрь

2022-02-01 00:56 UTC, AntonZelinsky commented on notion.py
> +            email = properties.Дежурный.people[0].person.email
Помнишь что нужно было сделать? Забирать из ноушена дежурного и брать только его email. Остальные поля нужно удалить.

2022-02-01 00:56 UTC, AntonZelinsky commented on notion.py
> +            if email:
А давай если нет email, то будем брость исключение от сюда. А в колбэках его будем ловить. Создай какое-нибудь кастомное исключение. Чуть позже везде прикрутим его.

2022-02-09 20:08 UTC, AntonZelinsky approved these changes

2022-02-09 20:08 UTC, AntonZelinsky commented on bot/__init__.py
> +                                          f'Студенты {", ".join([str(cohort.id) for cohort in users[user]])} когорты '
WTF? `users[user]]`

`for email, cohots in users:`

p.s.: сейчас в переменной user  в строке `for user in users:` находится не пользователь, а email

2022-02-09 20:08 UTC, AntonZelinsky commented on .env.example
> -DOMAIN_ADDRESS=
Домен используется для вебхуков

2022-02-09 20:08 UTC, AntonZelinsky commented on notion.py
> +                logging.error(f'Не найдено поле email среди данных, полученных из Notion.\n{properties}')
В каких случаях у пользователя может не быть email? Он ведь нужен для регистрации в самом ноушене. Мне кажется, это нереальный кейс.

2022-02-09 20:08 UTC, AntonZelinsky commented on notion.py
> +                logging.error(f'Не найдено поле email среди данных, полученных из Notion.\n{properties}')
И даже если бы тут отловилось это исключение, то оно бы обработалось и код пошёл дальше и скорее всего, сразу же упал бы.

2022-02-09 20:08 UTC, AntonZelinsky commented on notion.py
>          try:
Давай как весь этот try вынесем в отдельную функцию, так код красивее будет. Плюс, в except помимо пробрасывания ошибки наверх, добавь ещё логирование. А в него информацию, которая отправляется в запросе: дата и когорта. Можно ещё как-то содержимое исключения залогировать для большего контекста, может pprint поможет

2022-02-09 20:08 UTC, AntonZelinsky commented on notion.py
>          try:
А в следующем ПРе можно будет этот файл в класс переделать, для большей красоты.

2022-02-10 09:22 UTC, inferno2f commented on bot/__init__.py
> +                                          f'Студенты {", ".join([str(cohort.id) for cohort in users[user]])} когорты '
Порой мой мыслительный процесс меня самого удивляет.... )
Распаковывалось все нормально, но тащил я когорты действительно очень криво, залезая в словарик со всеми сегодняшними дежурными и доставая оттуда нужное значение через `users[user]`

Полностью согласен с твоим замечанием. ) Также заменю название переменных users и cohorts для большей ясности

2022-02-10 09:23 UTC, inferno2f commented on .env.example
> -DOMAIN_ADDRESS=
Я его решил отсюда убрать, т.к. свой локальный .env держу без него. Иначе бот не запускается.
Ок, верну

2022-02-10 09:27 UTC, inferno2f commented on notion.py
> +                logging.error(f'Не найдено поле email среди данных, полученных из Notion.\n{properties}')
> 

Я решил, что стоит предусмотреть вариант "сломанного" ответа от API ноушена (маловероятно, но возможность наверное есть).
При таком раскладе, если нам не удалось получить почту дежурного из ноушена - залогируем ошибку

2022-02-10 14:50 UTC, AntonZelinsky commented on notion.py
> +                logging.error(f'Не найдено поле email среди данных, полученных из Notion.\n{properties}')
Потом, добавим обработку исключений на самом вернем уровне. Поэтому, оно удет сыпаться как карточный домик и дойдёт до той обработки исключений

2022-02-10 15:20 UTC, AntonZelinsky approved these changes
Удали только обработку исключений и новое исключение и можешь мержить!

2022-02-10 15:20 UTC, AntonZelinsky commented on notion.py
> +                print(e)
Это не логирование, это какая-то ерунда. Выше же строчка с логированием, зачем нужна эта? Или у тебя логи не выводятся в консоль?

2022-02-10 15:20 UTC, AntonZelinsky commented on notion.py
> +                print(e)
Не, Влад, давай не будем тут перехватывать исключение. Иначе, таких исключений может быть очень много. Если тут будет исключене, то оно в любом случае пойдёт наверх

2022-02-10 15:41 UTC, merged