Schedule generator
AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum pull request #21
Opened 2022-02-01 18:35 UTC by AlexPunches

В настройках указываем на сколько дней от даты запуска хотим иметь расписание, в какой день недели и в котором часу запускать.

Запускался через `init_polling()`
а он со свежей версией питона (3.10) не хотел работать, потребовалось `idle()` на `Updater`
из-за этого пришлось немного вмешаться в запуск бота, 
но решение мягко говоря не очень изящное ;) Тут надо будет придумать что нибудь.

2022-02-02 00:37 UTC, AntonZelinsky reviewed
Блин, забыл что, хотел Влада позвать. Можешь параллельно это править, а Влад пусть поревьювит.

2022-02-02 00:37 UTC, AntonZelinsky commented on bot/__init__.py
>  def callback_evening_reminder(context: CallbackContext):
А давай вынесем эти функции в новый файл (можно назвать колбэкск) и переименуем колбэки так, чтобы не в начале, а в конце стояло слово callback — evening_reminder_callback

2022-02-02 00:37 UTC, AntonZelinsky commented on bot/__init__.py
> +def continue_schedule(context: CallbackContext):
Хорошо когда соблюдается структура, идут блок функций колбэков, блок инициализации, тогда их просто смотреть, а когда разбросаны по всему файлу, то это не удобно для восприятия

2022-02-02 00:37 UTC, AntonZelinsky commented on core/config.py
> +    schedule_extension_weekdays: tuple = (6,)  # воскресенье
👍🏻

2022-02-02 00:37 UTC, AntonZelinsky commented on bot/__init__.py
> +user_service: UserService = UserService(BackgroundTasks(), SessionLocal())
user_service не используется в этом файле

2022-02-02 00:37 UTC, AntonZelinsky commented on bot/__init__.py
> +    time = datetime.datetime.strptime(settings.schedule_extension_time, "%H:%M").time()
Можно сделать небольшой хелпер, которые будет приводить строку к времени. Так, уйдёт дублирование кода и он станет проще

2022-02-02 07:28 UTC, AlexPunches commented on bot/__init__.py
>                   f'юзернеймом {update.effective_chat.username} и id {update.effective_chat.id}')
Похоже, весь файл попадает под замес,
тогда можно и все кавычки сделать одинаковыми, например, одинарными.

2022-02-02 08:07 UTC, AlexPunches commented on bot/__init__.py
> +    dispatcher.job_queue.run_daily(continue_schedule, time, days=settings.schedule_extension_weekdays)
Почему бы не перейти на именованные аргументы?

2022-02-02 08:10 UTC, AlexPunches commented on helpers.py
> +def strptime(str_time):
Лучше поменять найвание функции, 
чтобы потом не путаться

2022-02-02 08:11 UTC, AlexPunches commented on notion.py
> +    Получить цикл дежурств наставнико из последовательности крайних дежурств.
*наставникоВ

2022-02-02 08:14 UTC, AlexPunches commented on notion.py
> +        # TODO: возможно ли одним запросом добавить все необходимые страницы?
увы, невозможно :(

2022-02-02 08:19 UTC, AlexPunches commented on bot/__init__.py
> +    defaults = telegram.ext.Defaults(tzinfo=timezone('Europe/Moscow'))
может быть настройку в окружение вынести?

2022-02-09 21:27 UTC, AntonZelinsky reviewed
Саша, посмотри комменты какие есть, я запущу у себя твою ветку, посмотрю что приходит в ответ от ноушен и среднего прокомментирую больше

2022-02-09 21:27 UTC, AntonZelinsky commented on bot/__init__.py
>  def start(update, context):
Увидев эту функцию впал в ступор, помню что делали какоие-то диалоги с регистрацией, а их тут нет.
Старт находится в другом файле, это рудимент. Удали пожалуйста эту функцию
https://github.com/AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum/blob/develop/handlers/conversation_handlers.py

2022-02-09 21:27 UTC, AntonZelinsky commented on bot/callbacks.py
> +def continue_schedule(context: CallbackContext):
```suggestion
def continue_schedule_callback(context: CallbackContext):
```

2022-02-09 21:27 UTC, AntonZelinsky commented on bot/callbacks.py
> +        if added_duties:
Если не добавилось, то тем более нужно залогировать

2022-02-09 21:27 UTC, AntonZelinsky commented on bot/__init__.py
> +        days=settings.schedule_extension_weekdays,
100% есть функция run_weekly

2022-02-09 21:27 UTC, AntonZelinsky commented on bot/callbacks.py
> +import logging
Давай не просто callbacks.py назовём, а jobs_callbacks.py, потому что колбэки могут быть и у обычных кнопок. Я что-то сразу не подумал об этом

2022-02-09 21:27 UTC, AntonZelinsky commented on bot/callbacks.py
> +import logging
Блин, и ты и Влад работали над этими функциями, будут небольшие конфликты

2022-02-09 21:27 UTC, AntonZelinsky commented on bot/callbacks.py
> +        if added_duties:
И делать это скорее не тут, а в том месте где это обнаруживается, чтобы в логи добавить больше контекста

2022-02-09 21:27 UTC, AntonZelinsky commented on notion.py
> +        response = client.pages.create(
Вынеси создание карточки в отдельную функцию.

2022-02-09 21:27 UTC, AntonZelinsky commented on notion.py
> +    client = create_client()
В нескольких местах создаётся клиент, Это плохо. Чуть позже, переделаем этот файл в класс и сделаем клиент приватным свойством. Так, появится структура и чёткость.

2022-02-09 21:27 UTC, AntonZelinsky commented on notion.py
> +    )
Тоже, давай в отдельную функцию вынесем

2022-02-14 22:27 UTC, AlexPunches commented on bot/callbacks.py
> +        if added_duties:
Добавил logging.error в notion.get_last_duties_by_cohort при недостаточных данных для расчета.

2022-02-14 22:28 UTC, AlexPunches commented on bot/__init__.py
> +        days=settings.schedule_extension_weekdays,
Викли все таки похоже нету,
из других, наверно, удобнее всего дейли
https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.jobqueue.html#telegram.ext.JobQueue

2022-02-14 22:33 UTC, AlexPunches commented on notion.py
> +    client = create_client()
бфла такая мысль, но самостоятельно не решился делать )

2022-02-15 23:41 UTC, AntonZelinsky commented on bot/__init__.py
> +        days=settings.schedule_extension_weekdays,
Сорян, значит я что-то попутал

2022-02-16 00:52 UTC, AntonZelinsky requested changes
Нужно дорабатывать саму идею генератора, так как наша программа, это помощник, но никак не обязательство регистрации пользователя в боте для генерации расписания. Сейчас, если пользователя нет, то всё приложение упадёт. Я сам об этом кейсе не подумал.( 

Если пользователя в базе нет, то нужно брать данные из старой карточки. Задача чуть-чуть усложняется, но не сильно. При генерации будут храниться 2 коллекции, одна с пользователями из базы, а другая с пользователями из ноушена. Сперва проверяем в одной, если пользователя у нас в базе нет, то берём значение из другой.

2022-02-16 00:52 UTC, AntonZelinsky commented on notion.py
> +            responseus = client.databases.query(
Опечатка. И если ты хотел responses, то это не совсем правильное название, так как у тебя один ответ от сервера, а не несколько.

2022-02-16 00:52 UTC, AntonZelinsky commented on notion.py
> +    actual_date = parse(last_duties[0].Дата.date.start).date()
Можно не подключать новую библиотеку, а сделать всё средствами стандартного питона
```suggestion
    actual_date = datetime.datetime.strptime(last_duties[0].Дата.date.start, '%Y-%m-%d').date()
```
Подключать новые библиотеки всегда плохо, если задачу можно решить без их

2022-02-16 00:52 UTC, AntonZelinsky commented on notion.py
> +    last_duties = sorted(last_duties, key=lambda duty: duty.Дата.date.start, reverse=True)
Избавится от **Дата**, для этого не нужно делать `response = Objectify(responseus)`. Тогда обращение к значению будет таким `duty['Дата']['date']['start']`. Хотя пока писал этот комент, то понял, что объектная структура лучше, чем избавиться от русского слова в названии. Поэтому, пусть наверно пока остаётся.

2022-02-16 00:52 UTC, AntonZelinsky commented on notion.py
> +            break
break выходит из цикла, ты уверен, что это то что ты хотел сделать??

2022-02-16 00:52 UTC, AntonZelinsky commented on notion.py
> +    for i, v in enumerate(future_duties):
i, v ???

2022-02-16 00:52 UTC, AntonZelinsky commented on notion.py
> +        # TODO: возможно ли одним запросом получить юзеров в список, и в цикле уже его использовать?
Так можно в одном запросе забрать всех пользователей:
```
return self.db.query(models.User).filter(User.notion_user_id.in_(list_id)).all()
```
Есть ещё способы, но этот быстрее нагуглился

2022-02-16 00:52 UTC, AntonZelinsky commented on notion.py
> +            date=duty['date'].isoformat(),
Объект даты по умолчанию хранит дату в isoformat

2022-02-16 00:52 UTC, AntonZelinsky commented on requirements.txt
> +python-dateutil==2.8.2
Избавься от этой библиотеки, выше я привёл пример как можно заменить её

2022-02-22 00:16 UTC, AlexPunches commented on notion.py
> +            responseus = client.databases.query(
Это, наверно, опечатка. Не помню чтобы так называл ))

2022-02-22 00:17 UTC, AlexPunches commented on notion.py
> +    actual_date = parse(last_duties[0].Дата.date.start).date()
тут я пытался предусмотерть случай, когда в календате когорты поле `Дата` укажут не совсем в таком формате как мы ожидаем. 
Как я понял, в ноушене это очень вероятно. 
Но это не точно )

2022-02-22 00:20 UTC, AlexPunches commented on notion.py
> +    for i, v in enumerate(future_duties):
Тут `i` это вроде как стандартное название для интдекса. 
А `v` как-то даже не используется, осмысленное название не нужно было.

Попробовал сделать без `v`. 
Вроде бы не менее надежно получилось, и читаемо, и вроде красиво

2022-02-22 00:22 UTC, AlexPunches commented on notion.py
> +            break
Да. Тут идея в том, что как только встретил юзера (ментора), который уже добавлен в цикл, то останавливаемся -> т.к. цикл держурства уже полный.

В идеале, наверно нужно что-то похитрее, 
но при наших условиях (по очереди, по одному) так тоже будет надежно работать.
Или как-то можно лучше?

2022-02-22 00:26 UTC, AlexPunches commented
Запилил с двумя коллекциями. Но потом прикинул и подумал,
может быть нам совсем тогда не обращаться к пользователям в БД при генерации расписания?
Нам же, впринципе, чтобы вставить карточку в календарь не нужно данных больше, чем есть в прошлых карточках.
Какбы копи-паст.

2022-02-22 15:34 UTC, AntonZelinsky requested changes

2022-02-22 15:34 UTC, AntonZelinsky commented on bot/jobs_callbacks.py
> +            logging.info(f'В {cohort.name} продлено расписание.')
Тогда, уже нет смысла от такого логирования. Залогируй сразу после того как будет сгенерировано для когорты расписание, а в этой функции вызывай только генерацию

2022-02-22 15:34 UTC, AntonZelinsky commented on notion.py
> +def add_duties_to_cohort(cohort: Cohort, max_days: int = 14):
Ну, и функцию лучше назвать `Generate schedule`, так будет сразу понятно, что это главная функция. 

Так же, хотелось бы сделать её первой, а все остальные, вспомогательные под ней разместить. Но можешь это сделать уже после мержа девелоп к себе. Там Влад уже этот файл переместил в другое место и сделал его классом.

2022-02-22 15:34 UTC, AntonZelinsky commented on notion.py
> +        return False
Я вообще предлагаю сделать одно исключение, которое будет бросаться при ошибках генерации расписания. Тут можно было бы вместо логирования бросить это исключение, а в колбэке перехватывать его, брать из него сообщение ошибки и логировать, а потом продолжать итерацию генерации расписания.

Это сделало бы код значительно чище и красивее. Сразу ушли бы такие проверки:
```
 if not last_duties:
        return False
```
а заодно и было бы отлавливание ошибок.

2022-02-22 15:34 UTC, AntonZelinsky commented on notion.py
> +    actual_date = datetime.datetime.strptime(last_duties[0].Дата.date.start, '%Y-%m-%d').date()
Не работает генерация!
![image](https://user-images.githubusercontent.com/1431279/155165510-d3b935fd-10ef-4156-a223-8796af926d9c.png)

![image](https://user-images.githubusercontent.com/1431279/155163306-0234c71d-e08f-4db8-af1f-f3f1c81393d3.png)

![image](https://user-images.githubusercontent.com/1431279/155165564-0ba5c5eb-5a45-49f1-a857-00db8e093501.png)

2022-02-22 19:04 UTC, AntonZelinsky commented on notion.py
> +        future_duties[i] = (dict(mentor=cycle[i % len(cycle)], date=duty_date))
Я всё думал, как ты генерируешь следующих наставников и не мог найти эту функцию. На самом деле, очень круто! Я бы точно не сразу до этого додумался!
Только вынести `cycle[i % len(cycle)` в отдельную переменную, для наглядности.

2022-02-22 19:04 UTC, AntonZelinsky commented on app/schemas.py
> +class DutyPageCreate(BaseModel):
Вообще, не вижу смысла использовать тут базовую модель. Это лишь усложняет и замедляет приложение.
Эти данные формируются в нашем приложении, модель передаётся в другую функцию и считываются там, на этом заканчивается их использование. Так что, от пидантика смысла нет.

2022-02-22 19:04 UTC, AntonZelinsky commented on notion.py
> +    return added
Тут наверх не нужно отдавать ничего. Просто в логер можно добавить информацию, что для такой-то когорты заполнили столько-то дней в расписании.

2022-02-22 19:04 UTC, AntonZelinsky commented on notion.py
> +    actual_date = datetime.datetime.strptime(last_duties[0].Дата.date.start, '%Y-%m-%d').date()
Окей, это не ошибка. Пока не будем разбираться что с этим делать. Это расписание будет залогировано, а когда такие случаи произойдут, то будем уже думать.

2022-03-06 17:33 UTC, AntonZelinsky reviewed
Осталось сделтаь обработку не выбранного дежурного в карточке и можно выпускать фитчу.

![image](https://user-images.githubusercontent.com/1431279/156934688-1efd97c5-3b9e-4018-ac5b-b02276b06be0.png)

2022-03-06 17:33 UTC, AntonZelinsky commented on test.py
> +    pass
Хорошо бы этот файл добавить в гитигнор. И пасс удалить)

2022-03-06 17:33 UTC, AntonZelinsky commented on helpers.py
> +def plural(count: int, forms: list) -> str:
Тогда уже захардкодь формы в этой функции, а то в случае других слов, могут быть другие порядки для форм.

2022-03-06 17:33 UTC, AntonZelinsky commented on core/services/notion_services.py
> +                mentor_name=duty['mentor']['name'],
Хорошо бы имя брать из базы, но в целом, окей. Посмотрим как работает и если что, то поправим.

2022-03-07 00:44 UTC, AlexPunches commented on helpers.py
> +def plural(count: int, forms: list) -> str:
Прям слово "день" просклонять?

Я думал сделать универсальную вспомогательную функцию. Чтобы в любом месте использовать.
Мне кажется докстринг поможет любое слово сделать в правильном порядке.

2022-03-07 01:53 UTC, AlexPunches commented on core/services/notion_services.py
> +                mentor_name=duty['mentor']['name'],
не помню точно, но вроде бы оно было из базы, 
но почему-то я это переделал. Сам уже не помню причину )

2022-03-07 23:18 UTC, AntonZelinsky commented on helpers.py
> +def plural(count: int, forms: list) -> str:
Ой, не, лучше 2 маленькие специализированные функции, чем одна супер крутая и навороченная, но со сложной логикой и потенциальными ошибками.
К тому же, обобщают тогда, когда есть необходимость, например уже есть 23-5 функций с одинаковой логикой, а не задолго заранее.

2022-03-07 23:43 UTC, AntonZelinsky approved these changes

2022-03-07 23:47 UTC, merged