Feature/dockerizing app
AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum pull request #24
Opened 2022-02-25 10:46 UTC by inferno2f

- Приложение можно развернуть через докер-компоуз в двух контейнерах (БД и бот)
- Небольшой фикс в классе NotionService: вместо инициализации клиента ноумена передаем экземпляр класса-клиента
- Апдейт ридми файла
- Минорный фикс относительного импорта

2022-02-25 19:59 UTC, AntonZelinsky requested changes

2022-02-25 19:59 UTC, AntonZelinsky commented on Dockerfile
> +COPY . .
Зачем 2 раза копи? Можно один раз сделать . . и всё будет работать

2022-02-25 19:59 UTC, AntonZelinsky commented on docker-compose.dev.yaml
> +      POSTGRES_DB: schedule_notifier
Эти штуки тоже, тогда нужно быть из локального файла

2022-02-25 19:59 UTC, AntonZelinsky commented on docker-compose.dev.yaml
> +      POSTGRES_DB: schedule_notifier
Вообще, давай сделаем отдельный файл. Этот переименуй в `docker-compose.postgres.yaml`, он будет поднимать базу для локальной разработки, а другой `docker-compose.yaml` разворачивать полноценно приложение

2022-02-25 19:59 UTC, AntonZelinsky commented on docker-compose.dev.yaml
> +      DATABASE_URL: postgresql://root:root@host.docker.internal:35432/schedule_notifier
Этому место в .env.
И мне кажется, что тут можно будет просто прописать `postgres`, вместо `host.docker.internal`. (как это было в последний спринтах)
Ну, и скорее всего прийдётся назвать контейнер базы не postgres, а как-то по другому, так как он сразу начнёт конфликтовать и ты не сможешь у себя запустить. Мне так кажется, но ты проверь сам)

2022-02-26 18:37 UTC, AntonZelinsky commented on docker-compose.dev.yaml
> +    command: python run.py
Давай так же на Uvicorn переделаем и запуск лучше делать в докерфайле: https://fastapi.tiangolo.com/deployment/manually/

2022-02-26 18:53 UTC, AntonZelinsky commented on docker-compose.dev.yaml
> +    command: python run.py
https://fastapi.tiangolo.com/deployment/docker/

2022-02-27 20:50 UTC, inferno2f commented on docker-compose.dev.yaml
> +      DATABASE_URL: postgresql://root:root@host.docker.internal:35432/schedule_notifier
Ок, попробую с Postgres. В теории как-то не обратил на это внимание.
Использовал `host.docker.internal` т.к. и на сайте [докера](https://docs.docker.com/desktop/mac/networking/#use-cases-and-workarounds) его нашел и на стэке в нескольких трэдах такое решение предлагали. Изначально у нас был localhost там и я никак не мог понять почему приложению никак не удается достучаться до бд в контейнере )

2022-02-27 20:52 UTC, inferno2f commented on Dockerfile
> +COPY . .
Согласен, делал видимо по аналогии с теорией... Но тут действительно получается лишний никому ненужный слой

2022-02-27 21:31 UTC, inferno2f commented on docker-compose.dev.yaml
> +      DATABASE_URL: postgresql://root:root@host.docker.internal:35432/schedule_notifier
UPD: с postgres в качестве имени хоста у меня не получилось поднять бд
<img width="1019" alt="Screen Shot 2022-02-28 at 12 31 08 AM" src="https://user-images.githubusercontent.com/25581875/155900714-07fa4b14-6300-47fa-abf7-3f43ee646d3b.png">

2022-02-28 16:46 UTC, AntonZelinsky approved these changes

2022-02-28 16:47 UTC, merged