Alchemy
AntonZelinsky/ScheduleNotifierForMentorsOfYandex.Praktikum pull request #7
Opened 2021-10-13 23:38 UTC by AlexPunches

Добавил алхимию и постгресс, но без ассинхронности
Собрал модели и pydantic

Чтобы потестировать нужно запустить докер контейнер
`docker-compose -f docker-compose.dev.yaml up`

и запустить сервер 
`uvicorn sql_app.main:app`

можно пощелкать по openapi [http://127.0.0.1:8000/docs](http://127.0.0.1:8000/docs)

уже есть пара ендпоинтов и несколько базовых функций

2021-10-14 01:44 UTC, AntonZelinsky requested changes
Будет тяжело, но придётся много чего удалить..(

2021-10-14 01:44 UTC, AntonZelinsky commented on docker-compose.dev.yaml
> +      - ./data:/var/lib/postgresql/data
Я думаю, нет смысла делать папку локально. 
Используй такую конструкцию для создания тома: `- postgres_data:/var/lib/postgresql/data/`

2021-10-14 01:44 UTC, AntonZelinsky commented on docker-compose.dev.yaml
> +      - ./data:/var/lib/postgresql/data
Тогда и в гит игноре не понадобится добавлять папку.
P.S. А что в этой папке за файлы находятся? Мне всегда было интересно, в каком виде постгрес хранит свои данные)

2021-10-14 01:44 UTC, AntonZelinsky commented on sql_app/crud.py
> +    return db_cohort
Ты оверхедишь! Сам придумываешь требования и реализовываешь их..(
У Яндекса есть такие майки, они значат, что проджект менеджер к которому приходят разработчики не их заказчик и он не может посоветовать как лучше. Это нужно узнавать у заказчика, что он хочет и что имел в виду под какой-то неочевидной формулировкой. Потому что когда реализовывают фитчу и отдают заказчику, а оказывается что это не то что он хотел, возникает много вопросов.
![image](https://user-images.githubusercontent.com/1431279/137233826-5cd48153-a2fd-40fa-a830-184065e4eae8.png)

Раз сделал, то пусть будет, но всё же, нужно идти по шагам!

2021-10-14 01:44 UTC, AntonZelinsky commented on sql_app/models.py
> +class Faculty(Base):
Давай всё таки удалим эту таблицу, так как от этого будет много лишних телодвижений, а расшаривать на другие факультеты мы пока не планируем.

2021-10-14 01:44 UTC, AntonZelinsky commented on sql_app/main.py
> +def read_faculties(
Сделай один эндпоинт который добавляет данные в базу, другой который получает. Всё остальное можно удалить..( Мы не будем использовать такие способы работы с АПИ. Я бы рассказал что правильнее взять, но ты запилил пол приложения за вечер, я не успел.)) 
Таким образом пишут только тогда, когда там планируется 1-2 эндпоинта и ничего больше.
Да и вообще, нам не нужны эти апишки сейчас, мы же не планируем делать фронт в ближайшее время.

2021-10-14 01:44 UTC, AntonZelinsky commented on sql_app/main.py
> +def read_faculties(
Валидации соответственно тоже не нужны.(( 
Я рассказывал уже про поддержание неиспользуемого кода и почему это плохо

2021-10-14 01:45 UTC, AntonZelinsky commented on sql_app/crud.py
> +    return db_cohort
Потом вспомнил, что мы же делаем не апи к сайту, а бота, поэтому, оставлять чтобы было не будем

2021-10-14 01:50 UTC, AntonZelinsky commented
Когда начнёшь править базу, скорее всего у тебя начнёт падать приложение с ошибками из-за того, что модель данных поменялась. Тут нужно подключать библиотеку alembic, но по хорошему, не нужно делать в этом ПР, потому что ты уже насоздвал много разных папок и файлов, и ещё с десяток таких же только запутают всё. В следующем ПР добавишь.

2021-10-14 01:53 UTC, AntonZelinsky commented
Вообще, структура папок будет приблизительно такой https://fastapi.tiangolo.com/tutorial/bigger-applications/
Но скорее всего, создадим ещё модуль core, где будут хранится штуки связанные с базой и которые будут шарится между двумя приложениями.

2021-10-14 15:48 UTC, AlexPunches commented on docker-compose.dev.yaml
> +      - ./data:/var/lib/postgresql/data
файлы постгресс-данных переместил из каталога приложения.

там в пострессе куча папок и файлов, там целый мир.
разобраться в них это наврено отдельный курс должен быть на ЯП :)
https://postgrespro.ru/docs/postgresql/13/storage-file-layout

базу поправить получилось легко, alembic не пригодились,
просто удалил старую ;)
данных всеравно пока небыло

2021-10-14 15:54 UTC, AlexPunches commented on sql_app/crud.py
> +    return db_cohort
Прикольная футболка :)

Удалил лишнее, оставил только добавить юзера и когорту, ну и гет_юзер и гет_когорту соответственно

2021-10-14 16:08 UTC, AlexPunches commented on sql_app/main.py
> +def read_faculties(
сделал один для когорты 
и один для юзера

согласен, фронт на данном этапе совсем не нужен
через openapi.json можно добавить все когорты,
а юзеры уже через телегу будут добавляться.

2021-10-14 23:04 UTC, AntonZelinsky requested changes

2021-10-14 23:04 UTC, AntonZelinsky commented on sql_app/models.py
> +class User(Base):
Создай папку core  и положи в него этот файл. Это общие модели между фронтом и ботом

2021-10-14 23:04 UTC, AntonZelinsky commented on sql_app/main.py
> +from typing import List
Папка  sql_app имеет плохое название. Создай папку app и файл _ _ init__.py и перенеси туда это содержимое

2021-10-14 23:04 UTC, AntonZelinsky commented on sql_app/main.py
> +from typing import List
Так же, в папке создать файл апи и в него поместить все роуты и регистрировать уже не на апп декоратор, а на 
апи роутер.
подключив предварительно такую штуку `router = APIRouter(tags=["Blogs"], prefix="/blog")`
Можно почитать тут https://fastapi.tiangolo.com/tutorial/bigger-applications/#apirouter

2021-10-14 23:04 UTC, AntonZelinsky commented on sql_app/main.py
> +from typing import List
А роутер регистрировать уже после создания приложения

2021-10-14 23:04 UTC, AntonZelinsky commented on sql_app/crud.py
> +from sqlalchemy.orm import Session
Этот файл корректнее уже назвать как сервис и положить в папку апп

2021-10-14 23:04 UTC, AntonZelinsky commented on sql_app/main.py
> +app = FastAPI()
Хорошо бы создавать приложение сразу в методе, для того чтобы конфигурировать его там и при повторном импорте не запускать приложение.
Пример привёл ниже, только назвать его лучше create_app и не создавать экземпляр в этом файле, пусть создаётся в корне приложения
https://github.com/nsidnev/fastapi-realworld-example-app/blob/master/app/main.py#L13

2021-10-14 23:11 UTC, AntonZelinsky commented
Глянь хорошую статейку, можно пару интересных архитектурный идей узнать https://testdriven.io/courses/fastapi-celery/app-factory/

2021-10-15 16:46 UTC, AlexPunches commented on sql_app/main.py
> +app = FastAPI()
сделал в методе create_app()

но вот не могу сообразить как создавать енкземляр в корне приложения, 
у нас сейчас там бот создается, и их надо как-то распораллелить

2021-10-15 22:22 UTC, AntonZelinsky reviewed
Ещё есть пару мелких вопросов, но уже поправим их в других ПРах.

2021-10-15 22:22 UTC, AntonZelinsky commented on docker-compose.dev.yaml
> +version: '3.9'
Создай файл readme и напиши что это за штука и как её запустить. Минимальная инструкция.

2021-10-15 22:22 UTC, AntonZelinsky commented on sql_app/database.py
> +SQLALCHEMY_DATABASE_URL = \
давай в кор тоже перенесём эту штуку. так как и бот и апи будет им пользоваться.

2021-10-15 22:22 UTC, AntonZelinsky commented on sql_app/schemas.py
> +from datetime import datetime
А схему в апп перенесём, так как она касается только апи

2021-10-16 15:10 UTC, AlexPunches commented on docker-compose.dev.yaml
> +version: '3.9'
сделал инструкцию как запустить докер и два эндпоинта.

а когда обьединим всю архитектуру, тогда соответственно редми перепишем

2021-10-17 00:49 UTC, AntonZelinsky approved these changes

2021-10-17 00:49 UTC, AntonZelinsky commented on README.md
> +#Квик старт
Почему-то заголовки не подтянулись. Скорее всего из-за того, что нет пробела после шарпа.

2021-10-17 00:49 UTC, AntonZelinsky commented on README.md
> +$ vim .env
Не пиши про вим. Лучше написать что нужно отредактировать этот файл и всё. 
Я например до сих пор не знак из его выйти! Мне недавно мало что не пришлось перезагружать сервер, из-за того, что я не мог выйти из него!) Я решил узнать, установлен ли вим на сервер по дефолту и это было ошибкой) Мне пришлось принудительно закрыть сессию с сервером. Гугл никак не помогал выйти из его..(

Да и пользователям винды он ничего не скажет

2021-10-17 00:49 UTC, AntonZelinsky commented on core/database.py
> +    "postgresql://root:root@localhost:35432/schedule_notifier"
АААА, что за хардкод???

2021-10-17 00:49 UTC, AntonZelinsky commented on README.md
> +Запустить докер-контейнер
Я думаю, тут стоит написать для чего нужен докер, чтобы развернуть локальную базу данныхв докере, но он вовсе не обязателен. И по хорошему, конфиг подключения к базе можно добавить в экзампл, поскольку мы его предлагаем в купе с приложением.

2021-10-18 13:11 UTC, merged

2021-10-18 15:53 UTC, AlexPunches commented on core/database.py
> +    "postgresql://root:root@localhost:35432/schedule_notifier"
Как раз на этом ПР зачитывался 12-factor App
а третий фактор один из немногих, который более менее понял :-)

2021-10-18 15:56 UTC, AlexPunches commented on README.md
> +$ vim .env
У меня тоже с вимом непростое знакомство было :)

а вот про пользователей виндовсов совсем не подумал. Виноват. Исправлюсь :)